### ISSUE TITLE
SD card not accessible on latest version of rflan

### ISSUE THREAD

**Issue by cnr-penten** [NextGenRF-Design-Inc/bytepipe_sdk#22]
1. Downloaded the latest ([v02.22.24](https://github.com/NextGenRF-Design-Inc/bytepipe_sdk/releases/tag/v02.22.24)) version of rflan for the 2cg from here: [rflan_xczu2cg-sbva484-1-e_sdcard.zip](https://github.com/NextGenRF-Design-Inc/bytepipe_sdk/releases/download/v02.22.24/rflan_xczu2cg-sbva484-1-e_sdcard.zip)
2. Flashed to SD card by following instructions here: https://github.com/NextGenRF-Design-Inc/bytepipe_sdk/tree/main/docs/sd_card
3. Booted up on the HDK using USB to serial port on J26
4. Run the command `ls` and see that not all of the files on the SD card are listed
5. Run `ExecuteScript test.txt` and it returns the error "CLI Script Drive not enabled", which seems to come from `ff.c` `FR_NOT_ENABLED`

Following the same steps with the older version [v12.08.22](https://github.com/NextGenRF-Design-Inc/bytepipe_sdk/releases/tag/v12.08.22) works.

Any ideas? Thanks

**Comment by g-anderson** [comment]
Thank you for the detailed bug report - we are looking into this issue.

**Comment by g-anderson** [comment]
This issue has been resolved in the latest release (v10.04.24).
